# Generated by Django 4.2.6 on 2023-11-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duree', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupe_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_de_places', models.PositiveIntegerField()),
                ('duree', models.PositiveIntegerField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.formation_all')),
            ],
        ),
    ]
